const indiviual={
    "EmployeeName":"",
    "PositionHeld":"",
    "EmployeeStartDate":"",
    "EmployeeID":"",
    "Department":"",
    "DepartmentSupervisor":"",
    "Today'sDate":"",
    "ReviewerName":"",
    "ReviewerTitle":"",
    "LastRevised":"",
    "PositionMission":{
        "Description":""
    },
    "GrowthPlan":{
        "Description":""
    },
    "KRA":{
        "K1":{
            "K1.1":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K1.2":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K1.3":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
        },
        "K2":{
            "K2.1":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K2.2":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K2.3":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
        },
        "K3":{
            "K3.1":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K3.2":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K3.3":{
                "Description":"",
                "Result":[],
                "Goal":""
            }
        },
        "K4":{
            "K4.1":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K4.2":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
            "K4.3":{
                "Description":"",
                "Result":[],
                "Goal":""
            },
        }
    }
}